const nomes = ['Adelha' , 'Alessandro' , 'Alfred' , 'Amanda' , 'Aparecida' , 'Arlindo' , 'Aurora' , 'Bento' , 'Camila' , 'Cristina' , 'Daliria' , 'Dulci' , 'Edward' , 'Elias' , 'Ester' , 'Frederico' , 'Gabriel' , 'Gabriela' , 'Helena' , 'Hilda' , 'Hiroto' , 'House' , 'Inácio' , 'Jade' , 'Jesse' , 'Joana' , 'Johnny' , 'Junior' , 'Karol' , 'Lourdes' , 'Maria' , 'Meredith' , 'Michele' , 'Monique' , 'Nelson' , 'Nicolas' , 'Nikhil' , 'Palmira' , 'Paola' , 'Rafaela' , 'Raj' , 'Ricardo' , 'Roberto' , 'Rodrigo' , 'Roger' , 'Ryan' , 'Sonia' , 'Ted', 'Tereza' ]
const figuras = ['Adelha.png' , 'Alessandro.png' , 'Alfred.png' , 'Amanda.png' , 'Aparecida.png' , 'Arlindo.png' , 'Aurora.png' , 'Bento.png' , 'Camila.png' , 'Cristina.png' , 'Daliria.png' , 'Dulci.png' , 'Edward.png' , 'Elias.png' , 'Ester.png' , 'Frederico.png' , 'Gabriel.png' , 'Gabriela.png' , 'Helena.png' , 'Hilda.png' , 'Hiroto.png' , 'House.png' , 'Inácio.png' , 'Jade.png' , 'Jesse.png' , 'Joana.png' , 'Johnny.png' , 'Junior.png' , 'Karol.png' , 'Lourdes.png' , 'Maria.png' , 'Meredith.png' , 'Michele.png' , 'Monique.png' , 'Nelson.png' , 'Nicolas.png' , 'Nikhil.png' , 'Palmira.png' , 'Paola.png' , 'Rafaela.png' , 'Raj.png' , 'Ricardo.png' , 'Roberto.png' , 'Rodrigo.png' , 'Roger.png' , 'Ryan.png' , 'Sonia.png' , 'Ted.png', 'Tereza.png' ]
const numeroAleatorio = Math.floor(Math.random() * 48) + 1;

console.log(numeroAleatorio);

criaCartao(
    '1',
    'Adelha',
    'descartado',
    'Adelha.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '2',
    'Alessandro',
    'descartado',
    'Alessandro.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '3',
    'Alfred',
    'descartado',
    'Alfred.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '4',
    'Amanda',
    'descartado',
    'Amanda.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '5',
    'Aparecida',
    'descartado',
    'Aparecida.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '6',
    'Arlindo',
    'descartado',
    'Arlindo.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '7',
    'Aurora',
    'descartado',
    'Aurora.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '8',
    'Bento',
    'descartado',
    'Bento.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '9',
    'Camila',
    'descartado',
    'Camila.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '10',
    'Cristina',
    'descartado',
    'Cristina.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '11',
    'Daliria',
    'descartado',
    'Daliria.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '12',
    'Dulci',
    'descartado',
    'Dulci.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '13',
    'Edward',
    'descartado',
    'Edward.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '14',
    'Elias',
    'descartado',
    'Elias.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '15',
    'Ester',
    'descartado',
    'Ester.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '16',
    'Frederico',
    'descartado',
    'Frederico.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '17',
    'Gabriel',
    'descartado',
    'Gabriel.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '18',
    'Gabriela',
    'descartado',
    'Gabriela.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '19',
    'Helena',
    'descartado',
    'Helena.png',
    'descartado.png',
    ''
 )
 criaCartao(
    '20',
    'Hilda',
    'descartado',
    'Hilda.png',
    'descartado.png',
    ''
 )
